### ISSUE TITLE
🪲When submitting buttons, the loading state will show for all the buttons

### ISSUE THREAD

**Issue by nsunami** [fleckz-nl/fleckz#192]
Is this a bit weird or ok? @jazellemaira 

https://github.com/user-attachments/assets/d228587d-58ac-451d-b982-bf920e1e1121

**Comment by jazellemaira** [comment]
It is a bit weird. How can we fix this?

**Comment by nsunami** [comment]
We may need to hook up separate state for each buttons. Currently, the loading state is coming from useMutation resolver, which is shared with all the buttons 😅
